# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('date', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('high', models.TextField(blank=True, null=True)),
                ('low', models.TextField(blank=True, null=True)),
                ('mid', models.TextField(blank=True, null=True)),
                ('last', models.TextField(blank=True, null=True)),
                ('bid', models.TextField(blank=True, null=True)),
                ('ask', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictyCand',
            fields=[
                ('date', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('open', models.TextField(blank=True, null=True)),
                ('close', models.TextField(blank=True, null=True)),
                ('high', models.TextField(blank=True, null=True)),
                ('low', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('candles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historicaldata.Candles')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('values', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historicaldata.Dicty')),
            ],
        ),
        migrations.AddField(
            model_name='markets',
            name='ticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historicaldata.Ticker'),
        ),
        migrations.AddField(
            model_name='candles',
            name='values',
            field=models.ManyToManyField(to='historicaldata.DictyCand'),
        ),
    ]
