# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicaldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('date', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('high', models.TextField(blank=True, null=True)),
                ('low', models.TextField(blank=True, null=True)),
                ('mid', models.TextField(blank=True, null=True)),
                ('last', models.TextField(blank=True, null=True)),
                ('bid', models.TextField(blank=True, null=True)),
                ('ask', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('coin', models.TextField(blank=True, null=True)),
                ('fiat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alldata',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='candles',
            name='values',
        ),
        migrations.RemoveField(
            model_name='markets',
            name='candles',
        ),
        migrations.RemoveField(
            model_name='markets',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='values',
        ),
        migrations.DeleteModel(
            name='Candles',
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='DictyCand',
        ),
        migrations.DeleteModel(
            name='Markets',
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
